
// CONVERSION FACTORS
export const METER_PER_INCH        = 0.0254
export const KILOGRAM_PER_POUND    = 0.453592

// WHEEL CONSTANTS
export const HUB_RADIUS_METERS     = 0.165 //6.5 INCHES APPROXIMATION
export const SPOKE_MASS_PERCENTAGE = 0.25
export const HUB_MASS_PERCENTAGE   = 0.20
export const RIM_MASS_PERCENTAGE   = 0.55

//TIRE CONSTANTS
export const SIDEWALL_MASS_PERCENTAGE = 0.25
export const TREAD_MASS_PERCENTAGE = 0.75